# Generated by Django 3.0.5 on 2020-04-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='destinatario',
            new_name='nome_destinatario',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='usuario',
        ),
        migrations.AddField(
            model_name='user',
            name='carrinho',
            field=models.ManyToManyField(to='api.ItemCarrinho'),
        ),
        migrations.AddField(
            model_name='user',
            name='enderecos',
            field=models.ManyToManyField(to='api.Endereco'),
        ),
    ]
