# Generated by Django 3.0.5 on 2020-05-07 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200406_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcarrinho',
            old_name='quantidade',
            new_name='qntd',
        ),
        migrations.RemoveField(
            model_name='user',
            name='carrinho',
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
