# Generated by Django 3.0.5 on 2020-05-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200509_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ano',
            field=models.PositiveIntegerField(default=2020, verbose_name='Ano (safra)'),
        ),
    ]
