# Generated by Django 3.0.5 on 2020-05-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_produto_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='oferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Oferta'),
        ),
    ]
