# Generated by Django 3.0.5 on 2020-05-15 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200513_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nome',
        ),
    ]
