# Generated by Django 3.0.5 on 2020-05-16 00:53

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_produto_nome'),
    ]

    operations = [
	UnaccentExtension()
    ]
