# Generated by Django 3.0.5 on 2020-05-16 01:06

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200516_0053'),
    ]

    operations = [
	UnaccentExtension()
    ]
