# Generated by Django 3.0.5 on 2020-05-18 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200516_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='enderecos',
        ),
        migrations.AddField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(default='Três Palmeiras', max_length=28),
        ),
        migrations.AddField(
            model_name='endereco',
            name='uf',
            field=models.CharField(default='RS', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Endereco'),
        ),
    ]
