# Generated by Django 3.0.5 on 2020-05-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200525_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='vol_alcoolico',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Vol. Alcoólico'),
        ),
    ]
