# Generated by Django 3.0.5 on 2020-05-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_grupo_vol_alcoolico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='classe',
            field=models.CharField(blank=True, choices=[('fino', 'Fino'), ('mesa', 'De mesa'), ('leve', 'Leve'), ('champagne', 'Champagne'), ('composto', 'Composto'), ('licoroso', 'Licoroso')], max_length=30),
        ),
    ]
