# Generated by Django 3.0.5 on 2020-06-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200525_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('assunto', models.CharField(blank=True, max_length=50, null=True)),
                ('mensagem', models.CharField(blank=True, max_length=200, null=True)),
                ('data_envio', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
