# Generated by Django 3.0.5 on 2020-06-06 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_mensagemcontato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagemcontato',
            options={'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterField(
            model_name='user',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Endereco'),
        ),
    ]
