# Generated by Django 3.0.5 on 2020-06-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200610_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemcontato',
            name='lido',
            field=models.BooleanField(default=False),
        ),
    ]
