# Generated by Django 3.0.5 on 2020-07-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200707_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContaEmail',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('analise', 'em análise'), ('aguardando', 'aguardando pag.'), ('preparando', 'preparando envio'), ('despachado', 'despachado'), ('entregue', 'entregue'), ('suspenso', 'suspenso'), ('cancelado', 'cancelado')], default='analise', max_length=20),
        ),
    ]
