# Generated by Django 3.0.5 on 2020-08-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200709_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
