# Generated by Django 3.0.5 on 2020-08-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200804_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
