# Generated by Django 3.0.5 on 2020-08-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200805_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.CharField(blank=True, default='https://louscher.s3-sa-east-1.amazonaws.com/Garrafa+de+vinho+ilustrativa.png', max_length=300, null=True),
        ),
    ]
